#ifndef DC_DAMAGE_CONFIG
#define DC_DAMAGE_CONFIG 1

// Name of library. Used mainly as a base for variable IDs. Must
// be unique vs all other libraries. Try to keep it short.
#define DC_DAMAGE_BASE_ID	"dcdam"

// Configuration
#define DC_DAMAGE_PROJECTILE_OFF			0
#define DC_DAMAGE_PROJECTILE_THROWN			2	// (OpenBOR uses 2 for its default throw system).

// Default values.
#define DC_DAMAGE_DEFAULT_INSTANCE			0
#define DC_DAMAGE_DEFAULT_ANCHOR_X			getlocalvar("self")
#define DC_DAMAGE_DEFAULT_ANCHOR_Y			getlocalvar("self")
#define DC_DAMAGE_DEFAULT_ANCHOR_Z			getlocalvar("self")
#define DC_DAMAGE_DEFAULT_DIRECTION_ADJUST	openborconstant("DIRECTION_ADJUST_OPPOSITE")
#define DC_DAMAGE_DEFAULT_DOL_FORCE			0
#define DC_DAMAGE_DEFAULT_DROP_FORCE		0
#define DC_DAMAGE_DEFAULT_DROP_VELOCITY_X	1.2
#define DC_DAMAGE_DEFAULT_DROP_VELOCITY_Y	3.0
#define DC_DAMAGE_DEFAULT_DROP_VELOCITY_Z	0.0
#define DC_DAMAGE_DEFAULT_ENT				getlocalvar("self")
#define DC_DAMAGE_DEFAULT_FORCE				0
#define DC_DAMAGE_DEFAULT_OTHER				getlocalvar("self")
#define DC_DAMAGE_DEFAULT_POSITION_X		NULL()
#define DC_DAMAGE_DEFAULT_POSITION_Y		NULL()
#define DC_DAMAGE_DEFAULT_POSITION_Z		NULL()
#define DC_DAMAGE_DEFAULT_PROJECTILE		DC_DAMAGE_PROJECTILE_OFF
#define DC_DAMAGE_DEFAULT_TYPE				openborconstant("ATK_NORMAL")

// Variable keys.
#define DC_DAMAGE_MEMBER_INSTANCE			DC_DAMAGE_BASE_ID + 0
#define DC_DAMAGE_MEMBER_ANCHOR_X			DC_DAMAGE_BASE_ID + 1
#define DC_DAMAGE_MEMBER_ANCHOR_Y			DC_DAMAGE_BASE_ID + 2
#define DC_DAMAGE_MEMBER_ANCHOR_Z			DC_DAMAGE_BASE_ID + 3
#define DC_DAMAGE_MEMBER_DIRECTION_ADJUST	DC_DAMAGE_BASE_ID + 4
#define DC_DAMAGE_MEMBER_DOL_FORCE			DC_DAMAGE_BASE_ID + 5
#define DC_DAMAGE_MEMBER_DROP_FORCE			DC_DAMAGE_BASE_ID + 6
#define DC_DAMAGE_MEMBER_DROP_VELOCITY_X	DC_DAMAGE_BASE_ID + 7
#define DC_DAMAGE_MEMBER_DROP_VELOCITY_Y	DC_DAMAGE_BASE_ID + 8
#define DC_DAMAGE_MEMBER_DROP_VELOCITY_Z	DC_DAMAGE_BASE_ID + 9
#define DC_DAMAGE_MEMBER_ENT				DC_DAMAGE_BASE_ID + 10
#define DC_DAMAGE_MEMBER_FORCE				DC_DAMAGE_BASE_ID + 11
#define DC_DAMAGE_MEMBER_OFFSET_X			DC_DAMAGE_BASE_ID + 12
#define DC_DAMAGE_MEMBER_OFFSET_Y			DC_DAMAGE_BASE_ID + 13
#define DC_DAMAGE_MEMBER_OFFSET_Z			DC_DAMAGE_BASE_ID + 14
#define DC_DAMAGE_MEMBER_OTHER				DC_DAMAGE_BASE_ID + 15
#define DC_DAMAGE_MEMBER_PROJECTILE			DC_DAMAGE_BASE_ID + 16
#define DC_DAMAGE_MEMBER_TYPE				DC_DAMAGE_BASE_ID + 17
#define DC_DAMAGE_MEMBER_THE_END			18

#endif // !DC_DAMAGE_CONFIG

