#include "data/scripts/dc_damage/config.h"

#import "data/scripts/dc_damage/damage_force.c"
#import "data/scripts/dc_damage/damage_land.c"
#import "data/scripts/dc_damage/damage_type.c"
#import "data/scripts/dc_damage/damage.c"
#import "data/scripts/dc_damage/direction.c"
#import "data/scripts/dc_damage/incoming_height.c"
#import "data/scripts/dc_damage/instance.c"
#import "data/scripts/dc_damage/lethality.c"
#import "data/scripts/dc_damage/drop.c"
#import "data/scripts/dc_damage/entity.c"
#import "data/scripts/dc_damage/instance.c"
#import "data/scripts/dc_damage/projectile.c"
#import "data/scripts/dc_damage/toss.c"
#import "data/scripts/dc_damage/velocity.c"
